apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p9t1ebb2x-go 
  janus-idp.io/tekton: p9t1ebb2x-go
  backstage.io/kubernetes-id: p9t1ebb2x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p9t1ebb2x-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml