apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: p9t1ebb2x-go-gitops
  description: This is GitOps manifest for p9t1ebb2x-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=p9t1ebb2x-go
    backstage.io/kubernetes-id: p9t1ebb2x-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: p9t1ebb2x-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:p9t1ebb2x-go
